site_name: API Logic Server
site_description: Instantly Create and Run Database Projects - Flask, APIs, SQLAlchemy, React Apps, Rules, Low-Code
repo_url: https://github.com/valhuber/ApiLogicServer
docs_dir: docs
strict: true
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.instant
    - kramdown
    - content.tooltips
    - navigation.footer
nav:
  - " ": index.md
  - Quick Start:
    - Express Eval: Install-Eval.md
    - Express Install: Install-Express.md
    - Detailed Install:
      - "Install API Logic Server": Install.md
      - "Create an API Logic Project": Create-ApiLogicProject.md
      - Execute an API Logic Project:
        - Execute in your IDE: IDE-Execute.md
        - Execute From Terminal: Execute.md
  - Tutorial:
    - "Tutorial": Tutorial.md
    - Sample-Database.md
    - "Deployment Tutorial": Tutorial-Deployment.md
    - "AI-driven Automation": Tech-AI.md
  - 1. Admin Web App:
    - "Automatic Admin App": Admin-Tour.md
    - Admin-Customization.md
  - 2. API:
    - "Automatic Multi-Table API": API.md
    - "Multi-Table APIs": API-Multi-Table.md
    - "Custom APIs": API-Customize.md
    - "Optimistic Locking": API-Opt-Lock.md
  - 3. Logic:
    - "Logic: Why": Logic-Why.md
    - "What Are the Rules": Logic.md
    - "Using Logic": "Logic-Use.md"
    - "Debugging Logic": "Logic-Debug.md"
    - "How: Logic and Agile": "Logic-Tutorial.md"
    - "Logic Operation": "Logic-Operation.md"
    - Rule Types:
      - "Constraints": "Logic-Type-Constraint.md"
      - "Allocation": "Logic-Allocation.md"
      - "Events": "Logic-Type-Events.md"
  - 4. Security:
    - "Role-based Authorization": Security-Overview.md
    - "Authorization": Security-Authorization.md
    - "Authentication": Security-Authentication.md
    - "Authentication Provider": Security-Authentication-Provider.md
    - "Activation": Security-Activation.md
    - "Swagger": Security-Swagger.md
  - "Using Your IDE": IDE-Customize.md
  - Database:
    - "Examples": Data-Model-Examples.md
    - Data-Model-Classes.md
    - Data-Model-Keys.md
    - Data-Model-Customization.md
    - "Connection Examples": Database-Connectivity.md
    - "Docker Test Databases": Database-Docker.md
    - "Multiple Databases": Data-Model-Multi.md
    - "Database Design": Data-Model-Design.md
    - "Table Filters": Data-Model-Filters.md
    - "Explore SQLAlchemy": Data-Model-Explore-SQLAlchemy.md
    - "Install pyodbc: SqlServer": Install-pyodbc.md
    - "Install psycopg2: Postgres": Install-psycopg2.md
  - DevOps - Containers:
    - "About Containers": DevOps-Containers.md
    - "DevOps Automation": DevOps-Automation.md
    - Create and Run Containers:
      - "Build Project Image": DevOps-Containers-Build.md
      - "Run Container": DevOps-Containers-Run.md
    - Cloud Deployment (Azure):
      - "Azure Setup": DevOps-Containers-Azure-Setup.md
      - "Dev Preview in Cloud": DevOps-Containers-Preview.md
      - "Managed Database": DevOps-Containers-Deploy.md
      - "Container Database": DevOps-Containers-Deploy-Multi.md
    - "Container Configuration": DevOps-Container-Configuration.md
    - Dev Containers:
      - "Dev Containers": DevOps-Docker.md
      - "GitHub and Codespaces": DevOps-GitHub.md
  - Architecture:
    - "What is API Logic Server": Architecture-What-Is.md
    - "Project Operation": Architecture-Project-Operation.md
    - "Declarative Automation": Architecture-Declarative-Automation.md
    - Internals:
      - "API Logic Server Development": Architecture-Internals.md
      - "Internals - CLI": Architecture-Internals-CLI.md
  - Agile / Testing:
    - "Agility With Behave": Behave.md
    - "Behave Logic Report": Behave-Logic-Report.md
  - Managing API Logic Projects:
    - "Structure": Project-Structure.md
    - "Rebuild": Project-Rebuild.md
    - "Virtual Environment": Project-Env.md
    - "Builders": Project-Builders.md
  - Troubleshooting.md
  - FAQs:
    - "Is this a Low Code approach?": FAQ-Low-Code.md
    - "Is this a Framework?": FAQ-Frameworks.md
    - "Is this a RETE Engine?": FAQ-RETE.md
    - "Is this a 4GL?": Tech-4GL.md
    - "Is this a Proven Technology?": Tech-Proven.md
    - "Is this like Live API Creator?": "FAQ-Live-API-Creator.md"
    - "Adoption Considerations?": Tech-Adoption.md
  - Tech Notes:
    - "About Tech Notes": Tech--Notes.md
    - "AI-driven Auto mysql": Tech-AI-mysql.md
    - "AI-driven Auto sqlite": Tech-AI-sqlite.md
    - "Working Software Now": Working-Software-Now.md
    - "Python as a DSL": Tech-DSL.md
    - "Python Tips": Tech-Python.md
    - "CodeSpaces": Tech-CodeSpaces.md
    - "Agile Integrations": Tech-Agile-Integrations.md
    - "Learning Flask": Tech-Learning-Flask.md
    - "Docker": Tech-Docker.md
    - "Using Slack": Tech-Slack.md
    - "Python Installation": Tech-Install-Python.md
    - "Python 3.11": Tech-Python-311.md
    - "Mkdocs Material": Tech-mkdocs-material.md
    - "CodeSpaces": Tech-CodeSpaces.md
    - "M1 Mac": Tech-m1.md
    - Personal:
      - "PyCon23 Talk": Tech-Conference-PyCon23-Talk.md
      - "PyCon23 Tutorial": Tech-Conference-PyCon23-Tutorial.md
      - "Conference": Tech-Conference.md
      - "Optimistic Locking": Optimistic-Locking.md
markdown_extensions:
  - toc:
      baselevel: 2
      title: On this Page
      toc_depth: 6
  - meta
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      title: "long"
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
extra_css:
  - stylesheets/extra.css