site_name: API Logic Server
site_description: Instantly Create and Run Database Projects - Flask, APIs, SQLAlchemy, React Apps, Rules, Low-Code
repo_url: https://github.com/ApiLogicServer/ApiLogicServer-src
docs_dir: docs
strict: false
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.instant
#    - navigation.tabs
    - kramdown
    - content.tooltips
    - navigation.footer
nav:
  - " ": index.md
  - GenAI:
    - "WebGenAI Website": WebGenAI.md
    - "WebGenAI Logic Editor": WebGenAI-logic-editor.md
    - "GenAI CLI": WebGenAI-CLI.md    
    - "Sample": Sample-Genai.md
  - Quick Start:
    - Doc-Home.md
    - Express Install: Install-Express.md
    - Detailed Install:
      - "Install API Logic Server": Install.md
      - "Create an API Logic Project": Create-ApiLogicProject.md
      - Execute an API Logic Project:
        - Execute in your IDE: IDE-Execute.md
        - Execute From Terminal: Execute.md
    - Express Eval (unavail): Install-Eval.md
  - Demos, Tutorial, Samples:
    - "GenAI Microservice Automation": Sample-Genai.md
    - "Tutorial": Tutorial.md
    - "AI - Copilot": Sample-AI.md
    - "Sample DB, Project": Sample-Database.md
    - "Sample Integration": Sample-Integration.md
    - "Sample DB, Project": Sample-Database.md
    - "Deployment Tutorial": Tutorial-Deployment.md
    - "Agile Tutorial": Tutorial-Agile.md
    - "Basic Self-Demo": Sample-Basic-Demo.md
    - "AI - ChatGPT, Agile": Tutorial-AI.md
    - "Sample Systems": Data-Model-Examples.md
  - 0. ApiLogicServer create:
    - "Create": Project-Structure.md
    - "Manager": Manager.md
    - "Create with Gen/AI on Web": WebGenAI.md
    - "Model Driven": Tech-DSL.md
    - "Create With Copilot": Project-Create-Copilot.md
    - "Rebuild": Project-Rebuild.md
    - "Virtual Environment": Project-Env.md
    - "Builders": Project-Builders.md
  - 1. Apps:
    - "Automatic Admin App": Admin-Tour.md
    - Admin-Customization.md
    - "Automatic Custom Apps":
      - "Custom Web Apps": App-Custom.md
      - "Ontimize Overview": App-Custom-Ontimize-Overview.md
      - "App Model Editor": App-Model-Editor.md
  - 2. API:
    - "Automatic Multi-Table API": API.md
    - "Multi-Table APIs": API-Multi-Table.md
    - "Self-Serve APIs": API-Self-Serve.md
    - "Custom APIs": API-Customize.md
    - "Optimistic Locking": API-Opt-Lock.md
  - 3. Logic:
    - "Logic: Why": Logic-Why.md
    - "Logic: Rule Types, Patterns": Logic.md
    - "Using Logic": "Logic-Use.md"
    - "Debugging Logic": "Logic-Debug.md"
    - "How: Logic and Agile": "Logic-Tutorial.md"
    - "Logic Operation": "Logic-Operation.md"
    - Rule Types:
      - "Constraints": "Logic-Type-Constraint.md"
      - "Sum": "Logic-Type-Sum.md"
      - "Formula": "Logic-Type-Formula.md"
      - "Copy": "Logic-Type-Copy.md"
      - "Allocation": "Logic-Allocation.md"
      - "Events": "Logic-Type-Events.md"
      - "Time/Date Stamping": Logic-Allocation-Time-Date.md
  - 4. Security:
    - "Overview": Security-Overview.md
    - "Getting Started with Security": Security-Getting-Started.md
    - "Role-based Authorization": Security-Authorization.md
    - "Login Authentication": Security-Authentication.md
    - "Activation: add-auth": Security-Activation.md
    - "Configure sql auth": Security-sql.md
    - "Configure Keycloak auth": Security-Keycloak.md
    - "Swagger": Security-Swagger.md
  - 5. Application Integration:
    - "Sample Integration": Sample-Integration.md
    - "Integration Mapping": Integration-Map.md
  - IDE - Customize, Manage:
    - "Customize Using Your IDE": IDE-Customize.md
    - "Fixup - missing attributes": IDE-Fixup-Attrs.md
    - "Import / Merge WebGenai": IDE-Import-WebGenAI.md
    - "Rebuild Test Data": IDE-Rebuild-Test-Data.md
  - Database:
    - "Connection Examples, Debug": Database-Connectivity.md
    - "Database Diagram": Database-Diagram.md
    - "Sample Databases": Data-Model-Examples.md
    - "Docker Test Databases": Database-Docker.md
    - Data-Model-Classes.md
    - Data-Model-Keys.md
    - Data-Model-Customization.md
    - "Database Design Changes": Database-Changes.md
    - "Data Model Quoted Columns": Data-Model-Quotes.md
    - "Multiple Databases": Data-Model-Multi.md
    - "Database Design": Data-Model-Design.md
    - "Table Filters": Data-Model-Filters.md
    - "Install pyodbc: SqlServer": Install-pyodbc.md
    - "Install psycopg2: Postgres": Install-psycopg2.md
    - "Using Postgresql": Data-Model-Postgresql.md
    - "Install Oracle Thick": Install-oracle-thick.md
    - "Sqlite": Data-Model-Sqlite.md
  - DevOps - Containers:
    - "About Containers": DevOps-Containers.md
    - "DevOps Automation": DevOps-Automation.md
    - Create and Run Containers:
      - "Build Project Image": DevOps-Containers-Build.md
      - "Run Container": DevOps-Containers-Run.md
    - Cloud Deployment (Azure):
      - "Azure Setup": DevOps-Containers-Azure-Setup.md
      - "Dev Preview in Cloud": DevOps-Containers-Preview.md
      - "Managed Database": DevOps-Containers-Deploy.md
      - "Container Database": DevOps-Containers-Deploy-Multi.md
    - "Container Configuration": DevOps-Container-Configuration.md
    - Dev Containers:
      - "Dev Containers": DevOps-Docker.md
      - "GitHub and Codespaces": DevOps-GitHub.md
  - Agile / Testing:
    - "Agility With Behave": Behave.md
    - "Behave Logic Report": Behave-Logic-Report.md
  - Architecture:
    - "What is API Logic Server": Architecture-What-Is.md
    - "Project Operation": Architecture-Project-Operation.md
    - "Declarative Automation": Architecture-Declarative-Automation.md
  - Internals:
    - "Internal Dev Procedures": Architecture-Internals.md
    - "Admin App Architecture": Architecture-admin-app-reuse.md
    - "Build, Load and Test": Architecture-Internals-BLT.md
    - "VENV (internals)": Architecture-venv.md
    - "Python (internals)": Architecture-python.md
    - "Internals - CLI": Architecture-Internals-CLI.md
    - Security:
      - "Authentication": Architecture-Security-Auth.md
  - Troubleshooting.md
  - FAQs:
    - "Is this a Low Code approach?": FAQ-Low-Code.md
    - "Is this a Framework?": FAQ-Frameworks.md
    - "Is this an AI Approach?": FAQ-AI.md
    - "Is this a RETE Engine?": FAQ-RETE.md
    - "Is this a 4GL?": Tech-4GL.md
    - "Is this a strategic investment?": FAQ-Strategic.md
    - "Is this a Proven Technology?": Tech-Proven.md
    - "Is this like Live API Creator?": "FAQ-Live-API-Creator.md"
    - "What about Maintenance?": FAQ-Maintenance.md
    - "Adoption Considerations?": Tech-Adoption.md
  - Tech Notes:
    - "About Tech Notes": Tech--Notes.md
    - "Keycloak DevNotes": Keycloak-devnotes.md
    - "API Appliance": Tech-Toaster.md
    - "Nat Lang Logic": Tech-Logic-Transcript.md
    - "AI Delivers Agile": Tech-AI.md
    - "Sample AI Demo ChatGPT": Sample-AI-ChatGPT.md
    - "AI-driven Auto mysql": Tech-AI-mysql.md
    - "AI-driven Auto sqlite": Tech-AI-sqlite.md
    - Tech-Budget-App.md
    - "Python Tips": Tech-Python.md
    - "CodeSpaces": Tech-CodeSpaces.md
    - "Agile Integrations": Tech-Agile-Integrations.md
    - "Learning Flask": Tech-Learning-Flask.md
    - "Docker": Tech-Docker.md
    - "Using Slack": Tech-Slack.md
    - "Python Installation": Tech-Install-Python.md
    - "Python 3.11": Tech-Python-311.md
    - "Mkdocs Material": Tech-mkdocs-material.md
    - "CodeSpaces": Tech-CodeSpaces.md
    - "M1 Mac": Tech-m1.md
    - "Product Detail": Product-Detail.md
    - "Product Overview": Product-Overview.md
    - Personal:
      - "Home": Home.md
      - "INFO": ApiLogicServer-create.md
      - "Recompute": Logic-Recompute.md
      - "PyCon23 Talk": Tech-Conference-PyCon23-Talk.md
      - "PyCon23 Tutorial": Tech-Conference-PyCon23-Tutorial.md
      - "Conference": Tech-Conference.md
      - "Optimistic Locking": Optimistic-Locking.md
      - "Old Home": Product-Detail.md
      - Page Links:
        - Tech-Agile.md
        - Tech-Learning.md
        - Tutorial-3.md
markdown_extensions:
  - toc:
      baselevel: 2
      title: On this Page
      toc_depth: 6
  - meta
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.emoji:
      title: "long"
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
 
extra_css:
  - stylesheets/extra.css